### ISSUE TITLE
清除浮动

### ISSUE THREAD

**Issue by wl05** [wl05/AntBlog#11]
## 浮动产生的影响

上代码：
```html
<!DOCTYPE html>
<html>

<head>
    <style type="text/css">
        .container {
            padding: 100px;
            border: 1px solid green;
            margin: 0 auto;
            width: 600px
        }
        
        .container-first {
            width: 500px;
            border: 2px solid black;
            padding: 5px;
            margin-top: 100px;
        }
        
        .container-float {
            width: 200px;
            height: 200px;
            border: 1px solid orange;
            color: orange;
            margin: 4px;
        }
        
        .container-text {
            color: green;
            border: 2px solid green;
        }
        
        .container-second {
            width: 500px;
            height: 100px;
            margin: 5px 0;
            border: 2px solid yellow;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="container-first">
            <div class="container-float">floatDivfloat left</div>
            <div class="container-text">
                container-text container-text container-text container-text container-text container-text container-text container-text
            </div>
        </div>
        <div class="container-second">
            container-second container-second container-second container-second container-second container-second
        </div>
    </div>
</body>

</html>

```

效果图：
![](https://user-gold-cdn.xitu.io/2018/11/21/16734f80289fa385?w=1612&h=1388&f=png&s=99743)

这是没有加浮动时候的效果，我们看到所有元素排列都很规矩。我们现在把浮动加上:
```css
 .container-float {
    width: 200px;
    height: 200px;
    border: 1px solid orange;
    color: orange;
    margin: 4px;
    float: right;
}
```
看看影响：
![](https://user-gold-cdn.xitu.io/2018/11/21/16734ff6eced6bb4?w=1624&h=1064&f=png&s=101601)
我们看到加上了浮动以后，出现了几点变化
1. 第一父元素```.container-first```高度出现了塌缩.
2. 第二兄弟元素```.container-text```移动到了浮动元素的位置，说明浮动元素脱离了文档流.
3. 第三我们看到无论是```.container-float```还是```.container-second```里面的文字都是围绕浮动元素排列的(其实这才是浮动真正的用途,我们现在用它来布局)。  
*我们平时所说的清除浮动就是为了解决1，2亮点所带来的影响*

## 清除浮动的方法
依据原理来区分大致无非就是两种方法：

1. clear
2. BFC

### 1. clear
clear 的原理实际就是看浮动元素是在受影响的元素右边还是左边。很多人理解不清楚这个意思动手实验一下就知道了，那我们这个例子来说，对于```.container-text```浮动元素在它的右边，所以我们想清除```.container-text```右边的浮动：

#### 1. 
```css
 .container-text {
    color: green;
    border: 2px solid green;
    clear: right
}
```

这里说一下clear的属性值，如果你想清除右边的浮动就用```clear:right```、如果想清除左边的浮动就用```clear: left```、如果两边都想清除那就```clear:both```，扯远了我们来看一下效果：

![](https://user-gold-cdn.xitu.io/2018/11/21/1673510a4e17f49e?w=1638&h=1398&f=png&s=99956)
我们可以看到```.container-text```又回到了之前的位置，同时父元素的高度也被重新撑回来了。当然这里有人会问如果:```.container-text```和 ```.container-float```的排列关系是这样的会怎样

```html
 <div class="container-first">
   <div class="container-text">
        container-text container-text container-text container-text container-text container-text container-text container-text
    </div>
    <div class="container-float">floatDivfloat left</div>
</div>
```

ok我们来实验一下，效果如下：

![](https://user-gold-cdn.xitu.io/2018/11/21/167351b827aa2fab?w=1640&h=982&f=png&s=89405)

这是因为浮动元素之前已经有兄弟元素存在，它会紧接着前面的兄弟元素排列，如果此时还想达到撑起父元素高度的效果，我们可以采用：

#### 2. 在父级元素的末尾追加一个块级元素
```html
 <div class="container">
    <div class="container-first">
        <div class="container-text">
            container-text container-text container-text container-text container-text container-text container-text container-text
        </div>
        <div class="container-float">floatDivfloat left</div>
        <div class="clear"></div>
    </div>
    <div class="container-second">
        container-second container-second container-second container-second container-second container-second
    </div>
</div>
```

```css
.container {
    padding: 100px;
    border: 1px solid green;
    margin: 0 auto;
    width: 600px
}

.container-first {
    width: 500px;
    border: 2px solid black;
    padding: 5px;
    margin-top: 100px;
}

.container-float {
    width: 200px;
    height: 200px;
    border: 1px solid orange;
    color: orange;
    margin: 4px;
    float: right;
}

.container-text {
    color: green;
    border: 2px solid green;
}

.container-second {
    width: 500px;
    height: 100px;
    margin: 5px 0;
    border: 2px solid yellow;
}

.clear {
    clear: both
}
```
效果如下：

![](https://user-gold-cdn.xitu.io/2018/11/21/16735378f7fef0ac?w=1650&h=1404&f=png&s=100024)
我们看到我们达到了清除浮动的效果，同时也撑起了父级元素的高度，但是这种方法增加了不必要的元素

#### 3. 利用伪元素

通过在元素末尾追加一个伪元素，并且将display设置block
```css
.container {
    padding: 100px;
    border: 1px solid green;
    margin: 0 auto;
    width: 600px
}

.container-first {
    width: 500px;
    border: 2px solid black;
    padding: 5px;
    margin-top: 100px;
}

.container-first:after {
    content: '.';
    height: 0;
    display: block;
    clear: both;
}

.container-float {
    width: 200px;
    height: 200px;
    border: 1px solid orange;
    color: orange;
    margin: 4px;
    float: right;
}

.container-text {
    color: green;
    border: 2px solid green;
}

.container-second {
    width: 500px;
    height: 100px;
    margin: 5px 0;
    border: 2px solid yellow;
}
```
这样同样能达到目的。

##### 小结一下:
这三种方法，基本原理都是一样的都是利用clear属性清除浮动。

### 2. BFC

简单解释一下什么是BFC:

##### BFC 定义：
　　BFC(Block formatting context)直译为"块级格式化上下文"。它是一个独立的渲染区域，只有Block-level box参与， 它规定了内部的Block-level Box如何布局，并且与这个区域外部毫不相干。

##### BFC布局规则：
* 内部的Box会在垂直方向，一个接一个地放置。
* Box垂直方向的距离由margin决定。属于同一个BFC的两个相邻Box的margin会发生重叠
* 每个元素的margin box的左边， 与包含块border 
* box的左边相接触(对于从左往右的格式化，否则相反)。即使存在浮动也是如此。
* BFC的区域不会与float box重叠。
* BFC就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素。反之也如此。
* 计算BFC的高度时，浮动元素也参与计算

##### 生成BFC

* 根元素
* float属性不为none
* position为absolute或fixed
* display为inline-block, table-cell, table-caption, flex, inline-flex
* overflow不为visible

具体的可以参考
[前端精选文摘：BFC 神奇背后的原理](考http://www.cnblogs.com/lhb25/p/inside-block-formatting-ontext.html)

然后我们可以试试：

```
 <!DOCTYPE html>
<html>

<head>
    <style type="text/css">
        .container {
            padding: 100px;
            border: 1px solid green;
            margin: 0 auto;
            width: 600px
        }
        
        .container-first {
            width: 500px;
            border: 2px solid black;
            padding: 5px;
            margin-top: 100px;
            overflow: auto
        }
        
        .container-float {
            width: 200px;
            height: 200px;
            border: 1px solid orange;
            color: orange;
            margin: 4px;
            float: right;
        }
        
        .container-text {
            color: green;
            border: 2px solid green;
        }
        
        .container-second {
            width: 500px;
            height: 100px;
            margin: 5px 0;
            border: 2px solid yellow;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="container-first">
            <div class="container-float">floatDivfloat left</div>
            <div class="container-text">
                container-text container-text container-text container-text container-text container-text container-text container-text
            </div>
        </div>
        <div class="container-second">
            container-second container-second container-second container-second container-second container-second
        </div>
    </div>
</body>

</html>

```

效果:

![](https://user-gold-cdn.xitu.io/2018/11/21/1673576dc955da4f?w=1644&h=1314&f=png&s=109009)

我们可以看到父元素的高度被浮动元素撑起来了，根据BFC的相关概念我们给```.container-first ``` 增加了``` overflow: auto``` 建构出BFC。同时BFC的高度计算包含浮动元素，所以浮动元素撑起了父元素的高度。

## 完结撒花

参考链接汇总：
1. [前端精选文摘：BFC 神奇背后的原理](https://www.cnblogs.com/lhb25/p/inside-block-formatting-ontext.html)
2. [清除浮动的四种方式及其原理理解](https://juejin.im/post/59e7190bf265da4307025d91)
3. [前端基础面试题@CSS篇](https://juejin.im/post/5af8e6aef265da0b9265b04c)
